### ISSUE TITLE
get rid of gawk dependency

### ISSUE THREAD

**Issue by unlimitedsola** [hangxingliu/wslgit#1]
`wslpath` is a new tool you can use to convert paths between Windows and Linux.  Run `wslpath` in a WSL environment.

The options are:
```
-a force result to absolute path format
-u translate from a Windows path to a WSL path (default)
-w translate from a WSL path to a Windows path
-m translate from a WSL path to a Windows path, with ‘/’ instead of ‘\\’
```

**Comment by unlimitedsola** [comment]
Example:
```
➜  ~ wslpath "C:\Users\loli"
/mnt/c/Users/loli
➜  ~ wslpath "C:\Windows\System32"
/mnt/c/Windows/System32
➜  ~
```

**Comment by hangxingliu** [comment]
but `wslpath` throw an exception when the parameter is not a path, for example:

``` bash
git clone git@github.com:hangxingliu/wslgit.git "C:\Projects\wslgit"
```

and it hard to replace linux path to windows path in stdout of `git`

**Comment by hangxingliu** [comment]
Similar issue: <https://github.com/andy-5/wslgit/issues/12>

**Comment by unlimitedsola** [comment]
`wslpath` will give non-zero return code if it failed to transform the input path, maybe we can leverage on this to test against each argument.
