### ISSUE TITLE
doesn't work anymore in Windows 10 Insider Preview Build 18342.8 (19H1)

### ISSUE THREAD

**Issue by erikrs** [hangxingliu/wslgit#10]
Windows just upgraded Windows (i'm on slow ring apparently). 

Since then wslgit doesn't work anymore, before it worked wonderfully !

eg. tried in command line:
C:\dev\wslgit>git.bat
/usr/bin/wslgit.sh: line 137: cd: C:\dev\wslgit: No such file or directory
fatal: can not cd to C:\dev\wslgit (C:\dev\wslgit)

**Comment by hangxingliu** [comment]
Can you post your `wsl.conf` and the output of `mount -t drvfs` on here because it seems like the drive C is not mounted in WSL.

Commands to get report info:

``` bash
cat /etc/wsl.conf
mount -t drvfs
```
