### ISSUE TITLE
[BUG] Path conversion regexp is too eager

### ISSUE THREAD

**Issue by rennex** [hangxingliu/wslgit#11]
**Describe the bug**
I wanted to use this program because I had C: mounted at `/c` in WSL (because that was needed for Docker). But my code lives in `C:\Users\username\code\`, and those paths got translated into `C:\Users\username\C:ode\` or something like that, essentially breaking any paths with directory names starting with "c", because those are also instances of the string `/c`.

**Comment by hangxingliu** [comment]
thanks for your report, patch later
