### ISSUE TITLE
mv: cannot move 'wslgit.sh' to '/usr/bin/wslgit.sh': Permission denied

### ISSUE THREAD

**Issue by Jeevz10** [hangxingliu/wslgit#18]
I tried moving the file to /usr/bin and it does not work. It comes back as permission denied. Any ideas on how to get around it?

**Comment by odelonmiranda** [comment]
`/usr/bin` is owned by the `root` user, so to be able write to that folder you need to use `sudo`

**Comment by Jeevz10** [comment]
this worked! thank you!
