### ISSUE TITLE
请问这个是集成在VS code的slidebar里的吗?

### ISSUE THREAD

**Issue by scp096** [hangxingliu/wslgit#2]

**Comment by hangxingliu** [comment]
这个脚本是为了让你能在VSCode中使用到安装在WSL里面的Git. 你给你的 VSCode 配置了 `"git.path": "C:\\path\\to\\git.bat"` 后左侧栏内的Git集成就能正常使用了

**Comment by scp096** [comment]
@hangxingliu ，谢谢回答，我也是同样方法配置，但是左侧栏git还是不起作用，不知道除了什么问题，或者说是我打开WSL里面项目的方式不对?

**Comment by scp096** [comment]
解决了，我是打开使用WSL的方式不对，之前在里面的/home/用户里面使用，发现不是正确的用法，现在改在windows重新用一遍就好了，感谢
