### ISSUE TITLE
Switch from bash to wsl command

### ISSUE THREAD

**Issue by jrock2004** [hangxingliu/wslgit#3]
With the WSL command now in windows, are you eventually going to upgrade your scripts?

**Comment by hangxingliu** [comment]
<https://github.com/hangxingliu/wslgit/blob/master/git.bat#L23>

Do you means replace `bash -c 'wslgit.sh %args%'` to `wsl -c 'wslgit.sh %args%'` in the file `git.bat` ?

---

Actually, I am using this wslgit in daily work on my Windows laptop. And I didn't meet any trouble. Is there benefit after replace `bash` to `wsl` ?

**Comment by jrock2004** [comment]
@hangxingliu sorry for not seeing this. There is nothing wrong, but it just updates to the command that MS recommends for interacting between each other

**Comment by hangxingliu** [comment]
Could you list some documents or pages about this things written by Microsoft to here, Thanks

**Comment by Dormanil** [comment]
Here we have [A Guide to Invoking WSL](https://blogs.msdn.microsoft.com/commandline/2017/11/28/a-guide-to-invoking-wsl/) and the within-mentioned [Multi-Distro Documentation](https://docs.microsoft.com/en-us/windows/wsl/wsl-config) showing the multitude of ways to spin up WSL.

**Comment by hangxingliu** [comment]
@Dormanil Thanks for your reference, I will update it in recent days
