### ISSUE TITLE
Remove trailing whitespaces from driver when converting

### ISSUE THREAD

**Issue by joaopluigi** [hangxingliu/wslgit#8]
Hey there,

I had some problems when trying to update my `wslgit.sh` to the last version `2019-02-08`. Debugging it, I found that my variable `MOUNTED_DRVFS` was getting some trailing whitespaces when splitted on `mount_len = split(_mount, mount_list, "\n");`. For that reason, the result of, for example, `to_unix_path_by_awk` function would be something like:

```
/c <SPACE>/apps/cool_app
```

Which was leading to error.

I solved by removing the whitespaces using `gsub` on `awk`

```
# Usage: to_unix_path_by_awk "$path"
function to_unix_path_by_awk() {
	.
        .
        .
	for(i = 1; i <= mount_len ; i += 2 ) {
	  gsub(/ /, "", mount_list[i])
	  gsub(/ /, "", mount_list[i+1])
	  if(driver != mount_list[i]) continue;
	    suffix = substr($0, 3); gsub(/\\/, "/", suffix); gsub("//", "/", suffix);
	    print mount_list[i+1] suffix;
        .
        .
        .
}
```

I'm not sure if this was the correct approach. Also, I don't know why I was getting the trailing spaces.

See my changes on: https://github.com/hangxingliu/wslgit/compare/master...joaopluigi:fix/convertion-whitespace?expand=1

**Comment by hangxingliu** [comment]
@joaopluigi Thanks for your report. I am also curious why there are extra white characters.

Can you report some information to here too:

1. The output of following commands:
```
mount -t drvfs
mount -t drvfs | base64 -
```
2. Your Windows version and OS build code. (you can find them in `Settings` > `System` > `About`)

---
By the way, I may reply later because of my work.

**Comment by hangxingliu** [comment]
And I guess the problem is caused by function `get_mounted_drvfs`:

``` bash
function get_mounted_drvfs() {
	# region need-to-be-replaced-in-unit-test
	#     The previous line is used for mark the following statments
	#     need to be replaced to other implementation for unit test (travis-CI)
	mount -t drvfs | awk '{
		if(split($0, lr, "type drvfs") < 2) next;
		if(split(lr[1], part, "on") < 2) next;

		drive = part[1];     gsub(/^\s/, "", drive);    gsub(/\s$/, "", drive);
		mount_to = part[2];  gsub(/^\s/, "", mount_to); gsub(/\s$/, "", mount_to);
		print toupper(drive) "\n" mount_to;
	}';
	# endregion need-to-be-replaced-in-unit-test
}
```
Maybe the `\s` in ` gsub(/^\s/, "", drive);    gsub(/\s$/, "", drive);` and `gsub(/^\s/, "", mount_to); gsub(/\s$/, "", mount_to);` should be replaced to `\s+`.

**Comment by joaopluigi** [comment]
Thanks for the answer! These are the info you asked for:

```
$ mount -t drvfs
C: on /c type drvfs (rw,noatime,uid=1000,gid=1000,metadata,case=off)
$ mount -t drvfs | base64 -
Qzogb24gL2MgdHlwZSBkcnZmcyAocncsbm9hdGltZSx1aWQ9MTAwMCxnaWQ9MTAwMCxtZXRhZGF0
YSxjYXNlPW9mZikK
```

Windows version: 1809 (I'm pretty sure I was getting this error on 1803 also)
OS build:  17763.316

**Comment by hangxingliu** [comment]
@joaopluigi And could you report the output of following command to here to, thanks

``` bash
awk --version
```

Because I found a Q&A on the StackOverflow:

> More generally, you can use `[[:space:]]` to match a space, a tab or a newline (GNU Awk also supports `\s`), and `[[:blank:]]` to match a space or a tab.

<https://stackoverflow.com/questions/29512854/how-to-define-a-space-in-a-regular-expression-in-awk>

**Comment by joaopluigi** [comment]
Ok, my `awk` is pointing to `mawk`

```
mawk 1.3.3 Nov 1996, Copyright (C) Michael D. Brennan

compiled limits:
max NF             32767
sprintf buffer      2040
```

**Comment by hangxingliu** [comment]
And you can try replace the implement of function `get_mounted_drvfs` to:

``` bash
function get_mounted_drvfs() {
	# region need-to-be-replaced-in-unit-test
	#     The previous line is used for mark the following statments
	#     need to be replaced to other implementation for unit test (travis-CI)
	mount -t drvfs | awk '
	function trim(s) { gsub(/^[[:space:]]+/, "", s); gsub(/[[:space:]]+$/, "", s); return s; }
	{
		if(split($0, lr, "type drvfs") < 2) next;
		if(split(lr[1], part, "on") < 2) next;

		drive = trim(part[1]); mount_to = trim(part[2]);
		print toupper(drive) "\n" mount_to;
	}';
	# endregion need-to-be-replaced-in-unit-test
}
```

And try again, It maybe working fine for you. @joaopluigi

**Comment by joaopluigi** [comment]
This solution did not work @hangxingliu

**Comment by hangxingliu** [comment]
@joaopluigi Have you updated that `wslgit.sh` to your WSL? Because I replaced `gawk` to `awk` in the script and working fine. (But I forgot copy `wslgit.sh` into WSL before test succeed)

---

And the reason why don't replace space characters after `get_mount_drvfs` is because the wrong path will be generated if mount path contains space char. (Eg. `/win disk/c`, although basically no one will do like this)

---

P.s. And my next reply will be appear in here after a few hours. I have to take a nap

**Comment by joaopluigi** [comment]
> @joaopluigi Have you updated that `wslgit.sh` to your WSL? Because I replaced `gawk` to `awk` in the script and working fine. (But I forgot copy `wslgit.sh` into WSL before test succeed)

I did the change directly on `/usr/bin/wslgit.sh` and tried. It only worked when I added back the `gsub` workaround

> And the reason why don't replace space characters after `get_mount_drvfs` is because the wrong path will be generated if mount path contains space char. (Eg. `/win disk/c`, although basically no one will do like this)

You're right. I agree

> P.s. And my next reply will be appear in here after a few hours. I have to take a nap

Haha go for it, get some rest

**Comment by hangxingliu** [comment]
@joaopluigi  Sorry for reply late. (I am busying on the work and graduation thesis recently) And i found the the root of problem about this issue in my scripts. and I will fix it in the latest commit.

The root of problem are:

1. the awk binary in `get_mount_drvfs` is `awk` but not `$AWK`. so the result will be converted by `gawk` but not `mawk` if you installed `gawk`
    - This command could explain: `readlink "$(readlink "$(which awk)")"`
2. `mawk` doesn't support `[[:space]]` in regex expression.

I will be grateful if you can give me a feedback of my latest commit for fix this issue.

**Comment by joaopluigi** [comment]
It worked just fine! 

Thanks for that
